name: admission_lottery
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  excel: ^3.0.0
  file_picker: ^6.1.1
  fluent_ui: ^4.7.7
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  get: ^4.6.6
  path_provider: ^2.1.1
  pdf: ^3.10.6

dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
